version: '2'

services:
    php:
        container_name: ddd-webshop-php
        image: php:7.1-cli
        volumes:
            - .:/var/www
        command: /bin/bash -c "cd /var/www; php vendor/bin/phpunit"
